ALTER TABLE events
    ADD COLUMN IF NOT EXISTS is_recurring BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS recurrence_rule TEXT,
    ADD COLUMN IF NOT EXISTS google_event_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS apple_event_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMP;
